# This is a dofile. For usage info visit https://github.com/roeldev/do

vars:
  ldf: "-X main.version=v1.0.1 -X main.buildDate=`date +%FT%T%z` -X main.gitBranch=develop -X main.gitCommit=`git describe --tags`"

# setup project, get dependencies
setup: go get -v -t -d ./...

# run tests with coverage and race detection
test: |
  go test -race -cover -coverprofile=coverage.out -v github.com/roeldev/go-errs
  go tool cover -func=coverage.out

bench: |
  go test -bench=.

example1: go run -race -ldflags="${ldf}" ./examples/1_basic/main.go
example2: go run -race -ldflags="${ldf}" ./examples/2_collector/main.go
example3: |
  go run ./examples/3_cli_flags/main.go
  go run -race -ldflags="${ldf}" ./examples/3_cli_flags/main.go -v
