name: Run tests
on:
  push:
    branches: [develop]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -race -v
